In [26]:
x=1
if x==4:
    print "hola"

In [18]:
if x != 3:
    print "x es diferente de 3"
elif x==4:
    print 4535
elif x<2:
    print "x es 444"
else: 
    print "no hay nada"

no hay nada


In [29]:
x=1
while x < 5:
    print "no es mayor que 5"
    
    print x
    x =x+1
    if x==4:
        break
else:
    print "el bloque acabo sin romperse"

no es mayor que 5
4
el bloque acabo sin romperse


In [13]:
c= 2
for c in 4:
    print c

TypeError: 'int' object is not iterable

In [36]:
cadena = raw_input("ingrese daots")

ingrese daots3


In [4]:
v = "5535"
print len(v)

b=v*2
print b

4
55355535


In [1]:
#secuencias: tipo de datos que contienen un conjunto de valores
var_tuplas = (1,2,4,5,2,3,22,"puede incluir varios tipos de variable",4,4534)
print var_tuplas
    
var_lista = [1,2,4,5,2,3,22,"puede incluir varios tipos de variable",4,4534]
print var_lista


(1, 2, 4, 5, 2, 3, 22, 'puede incluir varios tipos de variable', 4, 4534)
[1, 2, 4, 5, 2, 3, 22, 'puede incluir varios tipos de variable', 4, 4534]


In [2]:
var_lista == var_tuplas

False

In [3]:
for elemento in var_lista:
    print elemento

1
2
4
5
2
3
22
puede incluir varios tipos de variable
4
4534


In [4]:
# se puede preguntar si ay un dato en la tupla o lista
2 in var_lista

True

In [7]:
var_tuplas[0] ##para capturar valores tanto de tuplas o lsitas

1

In [8]:
var_lista[-1]  # para cojer el ultmo en python cuando es negativo empieza por el ultimo
var_tuplas[-1]

4534

In [9]:
var_lista[0:4] # para cojer los de 4 elementos empeazndo por el 0 

[1, 2, 4, 5]

In [16]:
lista_anidada = [[4,5],[1,2]] # una lista puede contener otras listas
print lista_anidada

[[4, 5], [1, 2]]


In [17]:
lista_anidada[0][1] #coje del primer elemento el elemento 1

5

# funciones

In [18]:
def nombre_funcion(argumentos_dela_funcion): # como se define una fnion 
    pass #argumentos
    

In [2]:
def cuadreado(x):
    """eleva un nemero al cuadrado"""
    y = x**2
    return y    ## es obligatorio para devolver una variable en una funcion

In [4]:
cuadreado(9)

81

In [24]:
def multiplicacion(x,y=3): #argumentos por defecto
    v=x*y
    return v

In [27]:
multiplicacion(3,)

9

In [3]:
x1 = 3
z1 = x1*[2,3]
z1

[2, 3, 2, 3, 2, 3]

In [8]:
x1 = "123456"
z1 = x1[2:5]
z1

'345'

In [18]:
lista_rango = [1,1,2,2,3,3,4,4,5,5,6,6]


In [39]:
for y in  range(3):
    print y

0
1
2


In [40]:
for r in range(1):
    print r

0


In [42]:
listi = [1]
for r in listi:
    print r

1


# MIDSQUARE


In [3]:
x = input("introduce un numero con 2n caracteres(semilla) ")
z = input("cantidad de numeros a generar")

y= x**2
print y
if len(str(y)) != 2*len(str(x)):
    print "2n**2 es diferente de 4n"
    lista = list(str(y))
    print lista
    aleatoria = "0."+str(lista[0]) + str(lista[1])
    print aleatoria
    
    
else:
    print "2n**2 es igual a 4n "
    lista = list(str(y))
    print lista
    aleatoria = "0."+str(lista[1]) + str(lista[2])
    print aleatoria
    

introduce un numero con 2n caracteres(semilla) 145326564756474567458534562365
cantidad de numeros a generar2
21119810423917795856523852059075285969449686793262074393225
2n**2 es diferente de 4n
['2', '1', '1', '1', '9', '8', '1', '0', '4', '2', '3', '9', '1', '7', '7', '9', '5', '8', '5', '6', '5', '2', '3', '8', '5', '2', '0', '5', '9', '0', '7', '5', '2', '8', '5', '9', '6', '9', '4', '4', '9', '6', '8', '6', '7', '9', '3', '2', '6', '2', '0', '7', '4', '3', '9', '3', '2', '2', '5']
0.21


 $$x_n = a(x_n-1)+b modulo m$$

In [5]:
import numpy

In [6]:
numpy.linalg.norm

<function numpy.linalg.linalg.norm>

In [4]:
import numpy as np

In [8]:
np.lookfor("solve")

Search results for 'solve'
--------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.linalg.lstsq
    Return the least-squares solution to a linear matrix equation.
numpy.linalg.tensorsolve
    Solve the tensor equation ``a x = b`` for x.
numpy.linalg._umath_linalg.solve
    solve the system a x = b, on the last two dimensions, broadcast to the rest.
numpy.linalg._umath_linalg.solve1
    solve the system a x = b, for b being a vector, broadcast in the outer dimensions.
numpy.distutils.misc_util.njoin
    Join two or more pathname components +
numpy.distutils.misc_util.minrelpath
    Resolve `..` and '.' from path.
numpy.distutils.system_info.UmfpackNotFoundError
    UMFPACK sparse solver (http://www.cise.ufl.edu/research/sparse/umfpack/)
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.cholesky
    Cholesky decomposition.
numpy.linalg.tensorinv
    Compute the 'inverse' of an N

# constantes y funciones matema...

In [9]:
np.e

2.718281828459045

In [10]:
np.pi

3.141592653589793

In [13]:
np.log (4)

1.3862943611198906

In [16]:
 ##crear un array
np.array([1,2,3,3,4,23,25])

array([ 1,  2,  3,  3,  4, 23, 25])

In [18]:
np.array([2,4,4.5,]) los convierte t a todos en flotante por uno de ellos lo es 

array([ 2. ,  4. ,  4.5])

In [19]:
np.array([2,4,4.5,"hola"])  3#no se puede

array(['2', '4', '4.5', 'hola'], 
      dtype='|S32')

In [6]:
m = np.array([2,4,4.5])
print m.dtype


float64


In [24]:
##para forzar el tipo de dato al array 
np.array([2,4,4,], dtype = float) 

array([ 2.,  4.,  4.])

In [7]:
## para cambiar un array de tipo de datos 
m.astype(int)

array([2, 4, 4])

In [11]:
from __future__ import braces ##mirar el error

SyntaxError: not a chance (<ipython-input-11-52aece39702a>, line 1)

# indexar arrays

In [14]:
a = np.array([ 
        [1,2,3],
        [4,5,6],
        [7,8,9]  
    ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[0]

array([1, 2, 3])

In [20]:
a[2,2]

9

In [24]:
a[0:2,1:2]##no s etoma e ultimo elemento  por esso solo coje fila 0 y 1 y columnas 1

array([[2],
       [5]])

In [26]:
a[:,1:2]  ##ahce lo mismo q arriba

array([[2],
       [5],
       [8]])

In [42]:
a[:,0:3:3]  ## con el ultimo :1 como solo los impares de posicion 

array([[1],
       [4],
       [7]])

In [43]:
a[:, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

# crear arrays 

In [45]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [47]:
np.zeros((3,8))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [48]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [49]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [50]:
np.identity(4).astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [56]:
##para optener el numero de filas y columnas de alguna matriz
matriz = np.identity(3)

matriz.shape

(3L, 3L)

In [58]:
##crear una matriz con la forma de otra
matriz2 = np.ones(matriz.shape)
matriz2

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [59]:
matriz3 = np.ones_like(matriz)
matriz3

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

#rangos

In [63]:
np.linspace(0,1, num = 10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [66]:
np.logspace(0,3,num=13,base=3)

array([  1.        ,   1.31607401,   1.73205081,   2.27950706,
         3.        ,   3.94822204,   5.19615242,   6.83852117,
         9.        ,  11.84466612,  15.58845727,  20.51556351,  27.        ])

In [72]:
x = np.linspace(3,4)
y = np.linspace(5,4)
t , tp = np.meshgrid(x,y)
t

array([[ 3.        ,  3.02040816,  3.04081633, ...,  3.95918367,
         3.97959184,  4.        ],
       [ 3.        ,  3.02040816,  3.04081633, ...,  3.95918367,
         3.97959184,  4.        ],
       [ 3.        ,  3.02040816,  3.04081633, ...,  3.95918367,
         3.97959184,  4.        ],
       ..., 
       [ 3.        ,  3.02040816,  3.04081633, ...,  3.95918367,
         3.97959184,  4.        ],
       [ 3.        ,  3.02040816,  3.04081633, ...,  3.95918367,
         3.97959184,  4.        ],
       [ 3.        ,  3.02040816,  3.04081633, ...,  3.95918367,
         3.97959184,  4.        ]])